title: Tarun Sreekar Parasa
logo: 
show_downloads: True
description: >
  Welcome to my data science portfolio! Kindly go through my projects, experience, education, skills, and professional development to learn more about my work and capabilities.
theme: jekyll-theme-minimal
font: Arial
include: ["_pages"]
footer: False
