title: Tarun Sreekar Parasa
logo: 
show_downloads: True
description: Detail-oriented Data Analyst with expertise in Google BigQuery, Python, and SQL. Skilled in statistical methods, data visualization, and storytelling for impactful reporting. Proven collaborator with clients and stakeholders, delivering actionable insights. Committed to leveraging data for business improvement and continuous professional growth.
theme: jekyll-theme-minimal
